# Generated by Django 5.0 on 2023-12-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_about_alter_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='uploads/')),
                ('image2', models.ImageField(upload_to='uploads/')),
                ('image3', models.ImageField(upload_to='uploads/')),
                ('image4', models.ImageField(upload_to='uploads/')),
                ('image5', models.ImageField(upload_to='uploads/')),
                ('image6', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='discription',
            field=models.CharField(max_length=500),
        ),
    ]
