# Generated by Django 5.0 on 2023-12-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_image1_portfolio_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
