# Generated by Django 4.0.3 on 2024-01-09 10:23

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_portfolio_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=50)),
                ('img', models.ImageField(upload_to='artical/')),
                ('Short_Discription', models.CharField(default=' ', max_length=200)),
                ('Large_Discription', ckeditor.fields.RichTextField()),
                ('createdName', models.CharField(default='', max_length=20)),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
