# Generated by Django 4.0.3 on 2024-01-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_artical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
